# Generated by Django 3.2.25 on 2025-07-07 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_add_streaming_fields'),
        ('music', '0006_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='genre',
            field=models.CharField(blank=True, choices=[('q', 'Unknown Genre'), ('a', 'Hip-Hop'), ('b', 'Rock'), ('c', 'Pop'), ('d', 'Jazz'), ('e', 'Classical'), ('f', 'Electronic'), ('g', 'Country'), ('h', 'Reggae'), ('i', 'Blues'), ('j', 'R&B/Soul'), ('k', 'Metal'), ('l', 'Folk'), ('m', 'Rock'), ('n', 'Punk'), ('o', 'Funk'), ('p', 'Disco'), ('r', 'Gospel'), ('s', 'Ska'), ('t', 'Latin'), ('u', 'Alternative'), ('v', 'K-Pop')], default='a', help_text='Song Genre', max_length=1),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='group_album',
            field=models.ForeignKey(blank=True, help_text='Album', null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.album'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='up_date',
            field=models.DateTimeField(default='03/11/2002', verbose_name='date published'),
        ),
    ]
