# Generated by Django 3.2.25 on 2025-11-18 05:54

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_background_image'),
        ('music', '0007_auto_20250706_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail', null=True, upload_to='videos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (mp4, mov, webm, ogg)', max_length=255, null=True, upload_to=music.models.upload_to_videos_folder),
        ),
    ]
