# Generated by Django 3.2.25 on 2025-02-27 03:52

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(blank=True, default='home/images/LMNlogo.jpg', null=True, upload_to=group.models.upload_to_group_folder_ac),
        ),
        migrations.AlterField(
            model_name='group',
            name='button',
            field=models.FileField(blank=True, default='home/images/LMNlogo.jpg', help_text='button.png', max_length=60, null=True, upload_to=group.models.upload_to_group_folder),
        ),
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, default='home/images/LMNlogo.jpg', help_text='Logopic.jpg', max_length=60, null=True, upload_to=group.models.upload_to_group_folder),
        ),
    ]
