"""
Django settings for labmunkznetwork project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&6=puxxn_1x^8ob2$t@(@7avuihy(@ri8set=fx8_c_^qma&6-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.labmunkzink.com', 'www.labmunkzink.com', '.labmunkz.com', 'www.labmunkz.com', 'labmunkzart.com', 'www.labmunkzart.com', '104.248.214.235', 'localhost', 'www.jivinscientists.com', '.jivinscientists.com', 'jivinscientists.com',]

AUTH_USER_MODEL = 'munkz.ArtistProfile'

CORS_ALLOW_ALL_ORIGINS = True
# or specify the allowed origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://www.labmunkzink.com",
]

APP_DIRS: True

SITE_ID = 1

# Application definition 'rest_framework','api.apps.ApiConfig','corsheaders',

INSTALLED_APPS = [
    'group.apps.GroupConfig',
    'home.apps.HomeConfig',
    'munkz.apps.MunkzConfig',
    'music.apps.MusicConfig',
    'polls.apps.PollsConfig',
    'shop.apps.ShopConfig', 
    'jobsite.apps.JobsiteConfig',
    'project.apps.ProjectConfig',
    'posts.apps.PostsConfig',
    'material.apps.MaterialConfig', 
    'schedule.apps.ScheduleConfig', 
    'timecard.apps.TimecardConfig',
    'todo.apps.TodoConfig',
    'client.apps.ClientConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
MIDDLEWARE = [
 #   'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'labmunkznetwork.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.global_context',
                'home.context_processors.cart_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'labmunkznetwork.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'labmunkzink',
        'USER': 'labmunk',
        'PASSWORD': 'L0vat0L0ve',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'MST'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
# Media settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Maximum upload size in bytes (20MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

env = environ.Env()
environ.Env.read_env()

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#MAIL_USE_SSL = False
#EMAIL_HOST_USER = 'letsreaddad@gmail.com'
#EMAIL_HOST_PASSWORD = 'hrjq hjrp nwtx qfud'
#DEFAULT_FROM_EMAIL = 'letsreaddad@gmail.com'