# Generated by Django 3.2.25 on 2025-02-13 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Artist first name', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Artist last name', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Artist biography')),
                ('profile_pic', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='uploads/artists/profile_pics/')),
                ('cover_photo', models.ImageField(blank=True, help_text='Cover photo', null=True, upload_to='uploads/artists/cover_photos/')),
                ('website', models.URLField(blank=True, help_text='Artist website', null=True)),
                ('resume', models.FileField(blank=True, help_text='Resume file', null=True, upload_to='uploads/artists/resumes/')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter handle URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('spotify_url', models.URLField(blank=True, help_text='Spotify artist profile')),
                ('total_hours_logged', models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours logged on projects', max_digits=10)),
                ('last_clock_in', models.DateTimeField(blank=True, help_text='Last clock-in time', null=True)),
                ('last_clock_out', models.DateTimeField(blank=True, help_text='Last clock-out time', null=True)),
                ('has_calendar_access', models.BooleanField(default=True, help_text='Can the artist access the calendar?')),
                ('has_task_management', models.BooleanField(default=True, help_text='Can the artist manage tasks?')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, help_text='Associated group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
